### ISSUE TITLE
not so user-friendly error messages

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#152]
`solium -d ./foobar`
If `foobar` doesn't exist, output:
```
binding.lstat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, lstat 'fucker'
    at Object.fs.lstatSync (fs.js:933:11)
    at dig (/Users/raghavdua/Desktop/github/Solium/node_modules/sol-digger/index.js:58:43)
    at lint (/Users/raghavdua/Desktop/github/Solium/lib/cli.js:149:23)
    at Object.execute (/Users/raghavdua/Desktop/github/Solium/lib/cli.js:289:22)
    at Object.<anonymous> (/Users/raghavdua/Desktop/github/Solium/bin/solium.js:11:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Need a more user friendly message

[DONE]

**Comment by duaraghav8** [comment]
Also, when only `solium` is written on cli, it crashes. Instead, it should print `--help` message

**Comment by duaraghav8** [comment]
Also, when we specify a plugin rule that couldn't be found, the error produced is `Cannot read property 'meta' of undefined`. Should be more friendly like `Rule plugin/blahblah does not exist.`

**Comment by duaraghav8** [comment]
Also, add different type of reporters (https://eslint.org/docs/user-guide/formatters/)

**Comment by duaraghav8** [comment]
v1.1.3
